spring.application.name=SB-PMS

#embedded tomcat port number
server.port = 1234

#Database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=xxxxxxxxxxxxxxx
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#application properties
pms.save.success="SUCCESS : Product Object Saved"
pms.update.success="SUCESS : Product Object Updated"
pms.delete.success="SUCESS : Product Object Deleted"

#application error properties
pms.invalid.product-details="FAILED : Invalid Product Details";
pms.invalid.product-notfound="FAILED : Product Not Found";

pms.db.failed="FAILED : DB Error"
